name: .NET
 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      
    - name: Restore NuGet Packages
      run: nuget restore TestActionMain\TestActionMain.sln
      
    - name: Restore Packages AppMain
      id: restoreAppMain
      run: nuget restore AppMain.sln
      env:
        nuget-version: 6.x

    - name: Build the Project with MSBuild
      run: msbuild TestActionMain\Dll.csproj /p:Configuration=Release /p:Platform="AnyCPU"
      
    - name: Build AppMain
      run: dotnet build AppMain\AppMain.csproj      
      
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.0.0
        release_name: Release v1.0.0
        body: This is the release of version 1.0.0
        draft: false
        prerelease: false

    - name: Upload Release Assets
      id: upload-release-assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ env.ARTIFACT_PATH }}
        asset_name: artifacts.zip
        asset_content_type: application/zip
